import type { Theme } from './types';

export const minimal: Theme = {
  id: 'minimal',
  displayName: 'Minimal · Linear',
  description: 'Clean modern. Hairline borders, no shadows, tight rhythm.',
  font: 'var(--font-geist-sans), "Inter", -apple-system, system-ui, sans-serif',
  fontMono: 'var(--font-geist-mono), "SF Mono", monospace',
  bg: '#FFFFFF',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  cardAlt: '#FAFAFA',
  border: '#EEEEEE',
  borderStr: '#D4D4D4',
  rule: '#F0F0F0',
  ink: '#0A0A0A',
  text: '#0A0A0A',
  muted: '#737373',
  subtle: '#A3A3A3',
  accent: '#5E6AD2',
  accentFg: '#FFFFFF',
  accentSoft: 'rgba(94,106,210,0.10)',
  chartA: '#0A0A0A',
  chartB: '#5E6AD2',
  chartGrid: '#F0F0F0',
  cardStyle: 'flat',
  radius: 8,
  fieldRadius: 6,
  padding: 24,
  cardShadow: 'none',
  cols2: '1fr 1.1fr',
  cols3: '1fr 1.05fr 1.6fr',
  headerH: 56,
  cardTints: null,
};
